### ISSUE TITLE
Custom color gradient for geomap

### ISSUE THREAD

**Issue by bmkramer** [hauschke/barcelonaDORI_map#2]
@hauschke  I've made some modifications in the ipynb file to generate the geomap with custom color gradient, using 'Barcelona yellow'. 

My new ipynb file has a lot of additional lines in the raw code from running it in Google Colab, so I'm linking it here instead: 
https://colab.research.google.com/drive/1YINhLbA4QbvvUIlTQFURvoCdxQu8-T1H?usp=sharing

Probably best for you to copy-paste the changes using your own workflow...

Changes:
- added two lines for importing packages/functions
- added new code block to define custom colormap
- calling custom color map when generating geomap
- used full url for loading countries_geo.json -  this should be switched back to loading the file from within the repo

Hope this works, let me know if there are any issues!

**Comment by hauschke** [comment]
Thanks @bmkramer, I added your changes. I added a print of the df with the country counts, too.
